# Generated by Django 4.0.3 on 2022-04-10 08:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='upload_time',
            field=models.DateTimeField(default=django.utils.timezone.now, unique=True),
            preserve_default=False,
        ),
    ]
