# Generated by Django 4.0.3 on 2022-05-17 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_category_num'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='category',
            name='num',
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
