# Generated by Django 4.0.3 on 2022-04-12 06:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_post_upload_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='upload_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 12, 15, 33, 27, 483078)),
        ),
    ]
